// Fake Weather API available cities
export const AVAILABLE_CITIES = [
    "New York", "London", "Los Angeles", "Tokyo", "Mumbai",
    "Chicago", "Toronto", "Sydney", "Paris", "Moscow",
    "Mexico City", "Rio de Janeiro", "Cairo", "Shanghai",
    "São Paulo", "Istanbul", "Kolkata", "Berlin", "Dubai",
    "Seoul", "Auckland", "Barcelona", "Cape Town", "Havana",
    "Montreal", "Kyoto", "Lima", "Nairobi", "Oslo", "Zurich",
    "Osaka", "Riyadh", "Bogotá", "Jakarta", "Buenos Aires",
    "Johannesburg", "Singapore", "Taipei", "Tehran", "Vancouver",
    "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra",
    "Wellington", "Christchurch", "Queenstown", "Edinburgh",
    "Dublin", "Lahore"
];

export type AvailableCity = typeof AVAILABLE_CITIES[number];

export const COUNTRY_OF_CITY: Record<AvailableCity, string> = {
    "New York": "États-Unis",
    "London": "Royaume-Uni",
    "Los Angeles": "États-Unis",
    "Tokyo": "Japon",
    "Mumbai": "Inde",
    "Chicago": "États-Unis",
    "Toronto": "Canada",
    "Sydney": "Australie",
    "Paris": "France",
    "Moscow": "Russie",
    "Mexico City": "Mexique",
    "Rio de Janeiro": "Brésil",
    "Cairo": "Égypte",
    "Shanghai": "Chine",
    "São Paulo": "Brésil",
    "Istanbul": "Turquie",
    "Kolkata": "Inde",
    "Berlin": "Allemagne",
    "Dubai": "Émirats Arabes Unis",
    "Seoul": "Corée du Sud",
    "Auckland": "Nouvelle-Zélande",
    "Barcelona": "Espagne",
    "Cape Town": "Afrique du Sud",
    "Havana": "Cuba",
    "Montreal": "Canada",
    "Kyoto": "Japon",
    "Lima": "Pérou",
    "Nairobi": "Kenya",
    "Oslo": "Norvège",
    "Zurich": "Suisse",
    "Osaka": "Japon",
    "Riyadh": "Arabie Saoudite",
    "Bogotá": "Colombie",
    "Jakarta": "Indonésie",
    "Buenos Aires": "Argentine",
    "Johannesburg": "Afrique du Sud",
    "Singapore": "Singapour",
    "Taipei": "Taïwan",
    "Tehran": "Iran",
    "Vancouver": "Canada",
    "Melbourne": "Australie",
    "Brisbane": "Australie",
    "Perth": "Australie",
    "Adelaide": "Australie",
    "Canberra": "Australie",
    "Wellington": "Nouvelle-Zélande",
    "Christchurch": "Nouvelle-Zélande",
    "Queenstown": "Nouvelle-Zélande",
    "Edinburgh": "Royaume-Uni",
    "Dublin": "Irlande",
    "Lahore": "Pakistan"
};

export const FR_CITY_NAME: Record<AvailableCity, string> = {
    "New York": "New York",
    "London": "Londres",
    "Los Angeles": "Los Angeles",
    "Tokyo": "Tokyo",
    "Mumbai": "Bombay",
    "Chicago": "Chicago",
    "Toronto": "Toronto",
    "Sydney": "Sydney",
    "Paris": "Paris",
    "Moscow": "Moscou",
    "Mexico City": "Mexico",
    "Rio de Janeiro": "Rio de Janeiro",
    "Cairo": "Le Caire",
    "Shanghai": "Shanghai",
    "São Paulo": "São Paulo",
    "Istanbul": "Istanbul",
    "Kolkata": "Calcutta",
    "Berlin": "Berlin",
    "Dubai": "Dubaï",
    "Seoul": "Séoul",
    "Auckland": "Auckland",
    "Barcelona": "Barcelone",
    "Cape Town": "Le Cap",
    "Havana": "La Havane",
    "Montreal": "Montréal",
    "Kyoto": "Kyoto",
    "Lima": "Lima",
    "Nairobi": "Nairobi",
    "Oslo": "Oslo",
    "Zurich": "Zurich",
    "Osaka": "Osaka",
    "Riyadh": "Riyad",
    "Bogotá": "Bogota",
    "Jakarta": "Jakarta",
    "Buenos Aires": "Buenos Aires",
    "Johannesburg": "Johannesburg",
    "Singapore": "Singapour",
    "Taipei": "Taipei",
    "Tehran": "Téhéran",
    "Vancouver": "Vancouver",
    "Melbourne": "Melbourne",
    "Brisbane": "Brisbane",
    "Perth": "Perth",
    "Adelaide": "Adélaïde",
    "Canberra": "Canberra",
    "Wellington": "Wellington",
    "Christchurch": "Christchurch",
    "Queenstown": "Queenstown",
    "Edinburgh": "Édimbourg",
    "Dublin": "Dublin",
    "Lahore": "Lahore"
};

export const AVAILABLE_WEATHERS = [
    "Clear sky",
    "Partly cloudy",
    "Cloudy",
    "Rain showers",
    "Sunny",
    "Rainy",
    "Scattered clouds"
];

export type AvailableWeathers = typeof AVAILABLE_WEATHERS[number];

export const WEATHER_TRANSLATION: Record<AvailableWeathers, string> = {
    "Clear sky": "Ciel clair",
    "Partly Cloudy": "Partiellement nuageux",
    "Partly cloudy": "Partiellement nuageux",
    "Cloudy": "Nuageux",
    "Rain showers": "Averses de pluie",
    "Sunny": "Ensoleillé",
    "Rainy": "Pluvieux",
    "Scattered clouds": "Nuages épars"
}

export const WEATHER_ADVICES: Record<AvailableWeathers, string> = {
    "Clear sky": "Lunettes de soleil",
    "Partly cloudy": "Vêtements légers",
    "Cloudy": "Prévoir un parapluie, juste au cas où",
    "Rain showers": "Prenez un parapluie (ou restez chez vous et faites un FIFA)",
    "Sunny": "Tenue légère",
    "Rainy": "Prenez un parapluie",
    "Scattered clouds": "Vêtements légers"
}

